### ISSUE TITLE
Gogs

### ISSUE THREAD

**Issue by makhov** [gophergala2016/servidor#1]
Guys, look at https://github.com/gogits/gogs

**Comment by pratikju** [comment]
I am already aware of gogs. Its just that I wanted my git server to be light weight and run without any database and prior configuration.
Anyhow, I don't see any point of opening this issue.
@makhov , Please feel free to reply to my concern here.

**Comment by makhov** [comment]
I just read "Motivation" section in readme about your troubles with GitLab and I guess, that maybe you don't know about Gogs.
